Repository Malkavianson/gamingdevsApi, pull requests merged in 2022-11, with the labels that each got.

#56 feat: recovery endpoint
  db.pdf
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#59 Email functional
  package.json
  src/users/users.controller.ts
  src/users/users.service.ts
  yarn.lock
Labels: bug

#60 Feat: password recover
  package.json
  src/users/users.controller.ts
  src/users/users.service.ts
  yarn.lock
Labels: Deploy

#61 Feat: add password recovery
  package.json
  src/users/users.controller.ts
  src/users/users.service.ts
  yarn.lock
Labels: Deploy

#65 Return Auth service
  src/auth/auth.service.ts
Labels: enhancement, Deploy

#67 fix: return Auth service
  src/auth/auth.service.ts
Labels: Deploy

#83 feat: loop
  src/main.ts
  src/utils/loop.ts
Labels: enhancement

#86 fix: time loop
  src/utils/loop.ts
Labels: bug

#100 feat: stop server endpoint
  src/app.controller.ts
  src/main.ts
  src/utils/loop.ts
Labels: enhancement

#101 feat: count time running application
  src/app.service.ts
  src/utils/loop.ts
Labels: enhancement

#102 feat: method convertTime
  src/app.service.ts
  src/utils/loop.ts
Labels: enhancement
